/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:10
*/

/**
 * MFTest.Header.view.main.Main Class
 *
 */
Ext.define('MFTest.Header.view.main.Main', {

    // {{{ extend

    extend: 'Ext.toolbar.Toolbar',

    // }}}
    // {{{ xtype

    xtype: 'mftest-header',

    // }}}
    // {{{ controller

    controller: 'mftest-header-main',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.Header.view.main.MainController',
        'MFTest.Header.view.main.MainModel'
    ],

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-header-main'
    },

    // }}}
    // {{{ height

    height: 50,

    // }}}
    // {{{ cls

    cls: 'x-mod-header',

    // }}}
    // {{{ items

    items: [{

        // {{{ Application Title

        reference       : 'btnDashboard',
        cls             : 'btn-dashboard',
        bind: {
            handler     : '{button.dashboard.handler}',
            text        : '{button.dashboard.text}'
        }

        // }}}

    }, '->', {

        // {{{ MyPage Button

        reference       : 'btnMyPage',
        bind: {
            handler     : '{button.mypage.handler}',
            text        : '{button.mypage.text}'
        }

        // }}}

    }, {

        // {{{ Logout Button

        reference       : 'btnLogout',
        bind: {
            handler     : '{button.logout.handler}',
            text        : '{button.logout.text}'
        }

        // }}}

    }]

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
