<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

// {{{ MFTest_EditListNoDB_Lists

/**
 * MFTest_EditListNoDB_Lists
 *
 * Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
 * http://www.xenophy.com
 *
 * generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:57
 */

class MFTest_EditListNoDB_Lists extends EditList {

    // {{{ autoconnect

    /**
     * データベース自動接続
     */
    public $autoconnect = true;

    // }}}
    // {{{ テーブル名

    public $table = 'editlistnodb';

    // }}}
    // {{{ フィールド設定

    public $fields = array(
        'textdata'
    );

    // }}}
    // {{{ Search Target

    public $searchTarget = 'textdata';

    // }}}
    // {{{ _validate

    protected function _validate($data) {

        $textdata = $data['textdata'];

        $errors = array();

        // 空チェック
        if ($textdata == '') {

            // "テキストを入力してください。"
            $errors['textdata'] = 'MFTest.EditListNoDB:Please enter textdata';

        }

        return $errors;

    }

    // }}}

}

// }}}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
