<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

// {{{ MFTest_EditOtherTable_Users

/**
 * MFTest_EditOtherTable_Users
 *
 * Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
 * http://www.xenophy.com
 *
 * generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:52
 */

class MFTest_EditOtherTable_Users extends EditEdit {

    // {{{ autoconnect

    /**
     * データベース自動接続
     */
    public $autoconnect = true;

    // }}}
    // {{{ テーブル名

    public $table = 'editothertable';

    // }}}
    // {{{ フィールド設定

    public $fields = array(
        'textdata'
    );

    // }}}
    // {{{ readData

    function readData($pk='') {

        return parent::readData($this->_getPk());
    }

    // }}}
    // {{{ _validate

    protected function _validate($data) {

        // データを変数へ代入
        $pk         = $this->_getPk();
        $textdata   = $data['textdata'];

        $errors = array();

        // 空チェック
        if ($textdata == '') {

            // "テキストを入力してください。"
            $errors['textdata'] = 'MFTest.EditOtherTable:Please enter textdata';

        }

        return $errors;

    }

    // }}}
    // {{{ _getUpdateData

    protected function _getUpdateData($param) {

        $data = parent::_getUpdateData($param);
        $data['pk'] = $this->_getPk();

        return $data;
    }

    // }}}

}

// }}}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
