/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 15:01:20
*/

/**
 * MFTest.TabletNavigation.view.main.MainController Class
 *
 */
Ext.define('MFTest.TabletNavigation.view.main.MainController', {

    // {{{ extend

    extend: 'MicroField.view.base.BaseController',

    // }}}
    // {{{ alias

    alias: 'controller.mftest-tabletnavigation-main',

    // }}}
    // {{{ init

    init: function() {

        var me = this;

        MicroField.getApplication().on('x-changescreen', me.onChangeScreen, me);
    },

    // }}}
    // {{{ control

    control: {

        'mftest-tabletnavigation': {

            // {{{ itemclick

            itemclick: function(row, model) {

                var me = this;

                if (!model.isLeaf()) {

                    if (model.isExpanded()) {
                        model.collapse();
                    } else {
                        model.expand();
                    }

                } else {

                    if (model.data.hrefTarget) {

                        if (MicroField.getApplication().fireEvent('x-beforechangescreen')) {

                            location.href = model.data.hrefTarget;

                        } else {

                            return false;

                        }
                    }
                }
            }

            // }}}

        }

    },

    // }}}
    // {{{ listen

    listen: {

        // {{{ store

        store: {

            // {{{ MFTest.TabletNavigation.store.Tree

            '#MFTest.TabletNavigation.store.Tree': {

                // {{{ load

                load: function(store, records, successful, eOpts) {

                    if (!successful) {

                        // 通信エラー処理
                        MicroField.support.failure(

                            // "内部エラー"
                            "Internal Error",

                            // "予期しないエラーが発生しました。"
                            "An unexpected error has occurred"
                        );

                    }

                    var me = this,
                        root = store.getNodeById('root'),
                        f;

                    f = function(node) {

                        node.updateInfo(true, {
                            text: _(node.data.text)
                        });

                        if (node.hasChildNodes() === true) {

                            node.eachChild(function(subnode) {
                                f(subnode);
                            });
                        }

                    };

                    root.eachChild(function(node) {
                        f(node);
                    });

                    // 項目選択
                    me.onChangeScreen('#' + MicroField.getApplication().getCurrentScreenName());

                }

                // }}}

            }

            // }}}

        }

        // }}}

    },

    // }}}
    // {{{ onChangeScreen

    onChangeScreen: function(name) {

        var me      = this,
            view    = me.getView(),
            sm      = view.getSelectionModel(),
            store   = view.getStore(),
            target;

        target = store.findBy(function(record, id) {
            return record.get('hrefTarget') === (name);
        });

        if (target !== -1) {

            // イベントサスペンド
            view.suspendEvents(false);

            // 項目選択
            sm.select(target);

            // イベントレジューム
            view.resumeEvents(false);
        }
    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
