/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
This file is part of MicroField 2.0

Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:12
*/

/**
 * MFTest.TabletNavigation.view.main.Main Class
 *
 */
Ext.define('MFTest.TabletNavigation.view.main.Main', {

    // {{{ extend

    extend: 'Ext.panel.Panel',

    // }}}
    // {{{ xtype

    xtype: 'mftest-tabletnavigation',

    // }}}
    // {{{ ui

    ui: 'tabletnavigation',

    // }}}
    // {{{ controller

    controller: 'mftest-tabletnavigation-main',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.TabletNavigation.view.main.MainController',
        'MFTest.TabletNavigation.view.main.MainModel'
    ],

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-tabletnavigation-main'
    },

    // }}}
    // {{{ plugins

    plugins: 'responsive',

    // }}}
    // {{{ responsiveConfig

    responsiveConfig: {
        tall: {
            region          : 'north',
            headerPosition  : 'left'
        },
        wide: {
            region          : 'west',
            headerPosition  : 'top'
        }
    },

    // }}}
    // {{{ config

    config: {

        // {{{ cls

        cls: 'x-mod-tabletnavigation'

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
