/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
This file is part of MicroField 2.0

Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:12
*/

/**
 * MFTest.TabletNavigation.view.main.MainController Class
 *
 */
Ext.define('MFTest.TabletNavigation.view.main.MainController', {

    // {{{ extend

    extend: 'MicroField.view.base.BaseController',

    // }}}
    // {{{ alias

    alias: 'controller.mftest-tabletnavigation-main',

    // }}}
    // {{{ init

    init: function() {

        var me      = this,
            view    = me.getView();

        // データ読み込み
        MicroField.rpc.MFTest.TabletNavigation.Menu.readData(Ext.Function.pass(me.onReadData, [], me));
    },

    // }}}
    // {{{ control

    control: {

        'mftest-tabletnavigation': {
            changeregion        : 'onChangeregion',
            beforechangeregion  : 'onBeforeChangeregion'
        }

    },

    // }}}
    // {{{ onSelectMenu

    onSelectMenu: function(target) {

        if (target.hrefTarget) {
            location.href = target.hrefTarget;
        }

    },

    // }}}
    // {{{ onBeforeChangeregion

    onBeforeChangeregion: function(o, region) {

        this.getView().items.each(function(btn) {
            btn.hideMenu();
        });

    },

    // }}}
    // {{{ onChangeregion

    onChangeregion: function(o, region) {

        var me      = this,
            view    = me.getView();

        view.items.each(function(btn) {

            if (region === 'west') {
                btn.menuAlign = 'tl-bl?';
            } else if (region === 'north') {
                btn.menuAlign = 'tl-tr?';
            }

        });

        if (region === 'west') {
            view.setHeight(100);
        } else if (region === 'north') {
        }

    },

    // }}}
    // {{{ onReadData

    onReadData: function(data) {

        var me      = this,
            view    = me.getView(),
            roots   = data.children;

        Ext.iterate(roots, function(item) {

            var menuAlign;

            if (view.region === 'west') {
                menuAlign = 'tl-tr?';
            } else if (view.region === 'north') {
                menuAlign = 'tl-bl?';
            }

            var o = {
                xtype       : 'button',
                cls         : item.cls,
                hrefTarget  : item.hrefTarget,
                text        : _(item.text),
                width       : item.width,
                menuAlign   : menuAlign,
                handler     : me.onSelectMenu
            };

            if (item.children) {

                var menu = o.menu = [];

                Ext.iterate(item.children, function(child) {
                    menu.push({
                        cls         : 'tabletnavigation',
                        hrefTarget  : child.hrefTarget,
                        text        : _(child.text),
                        width       : 150,
                        height      : 100,
                        handler     : me.onSelectMenu
                    });
                });

            }

            view.add(o);

        });

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
