/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 15:01:20
*/

/**
 * MFTest.TabletNavigation.view.main.Main Class
 *
 */
Ext.define('MFTest.TabletNavigation.view.main.Main', {

    // {{{ extend

    extend: 'Ext.tree.Panel',

    // }}}
    // {{{ xtype

    xtype: 'mftest-tabletnavigation',

    // }}}
    // {{{ controller

    controller: 'mftest-tabletnavigation-main',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.TabletNavigation.view.main.MainController',
        'MFTest.TabletNavigation.view.main.MainModel'
    ],

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-tabletnavigation-main'
    },

    // }}}
    // {{{ store

    store: 'MFTest.TabletNavigation.store.Tree',

    // }}}
    // {{{ config

    config: {

        // {{{ cls

        cls: 'x-mod-navigation',

        // }}}
        // {{{ rootVisible

        rootVisible: false,

        // }}}
        // {{{ animate

        animate: false,

        // }}}
        // {{{ expanded

        expanded: true,

        // }}}
        // {{{ items

        title: _('MFTest.TabletNavigation:Title')

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
