/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:19
*/

/**
 * MFTest.EditListNoDB.model.List Class
 *
 */
Ext.define('MFTest.EditListNoDB.model.List', {

    // {{{ extend

    extend: 'Ext.data.Model',

    // }}}
    // {{{ fields

    fields: [
        {name: 'pk', type: 'int'},
        'textdata',
        'modified',
        'created'
    ]

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
