/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:55
*/

/**
 * MFTest.EditListOtherScreenName.view.edit.EditController Class
 *
 */
Ext.define('MFTest.EditListOtherScreenName.view.edit.EditController', {

    // {{{ extend

    extend: 'MicroField.view.editlist.EditController',

    // }}}
    // {{{ alias

    alias: 'controller.mftest-editlistotherscreenname-edit'

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
