/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:17
*/

/**
 * MFTest.EditListOtherScreenName.view.list.List Class
 *
 */
Ext.define('MFTest.EditListOtherScreenName.view.list.List', {

    // {{{ extend

    extend: 'MicroField.view.editlist.List',

    // }}}
    // {{{ xtype

    xtype: 'mftest-editlistotherscreenname-list',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.EditListOtherScreenName.view.list.ListController',
        'MFTest.EditListOtherScreenName.view.list.ListModel',
        'Ext.selection.CheckboxModel',
        'MicroField.form.SearchField'
    ],

    // }}}
    // {{{ controller

    controller: 'mftest-editlistotherscreenname-list',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-editlistotherscreenname-list'
    },

    // }}}
    // {{{ store

    store: 'MFTest.EditListOtherScreenName.store.Lists',

    // }}}
    // {{{ columns

    columns: [{
        text        : _('MFTest.EditListOtherScreenName:column.Textdata'),
        dataIndex   : 'textdata',
        flex        : 1
    }],

    // }}}
    // {{{ api

    api: {
        remove  : 'MicroField.rpc.MFTest.EditListOtherScreenName.Lists.removeData'
    },

    // }}}
    // {{{ config

    config: {

        // {{{ selModel

        selModel: {
            selType: 'checkboxmodel'
        },

        // }}}
        // {{{ tbar

        tbar: [{

            // {{{ 新規追加ボタン

            reference       : 'btnAdd',
            bind: {
                handler     : '{button.add.handler}',
                text        : '{button.add.text}'
            }

            // }}}

        }, {

            // {{{ 編集ボタン

            reference       : 'btnEdit',
            bind: {
                handler     : '{button.edit.handler}',
                text        : '{button.edit.text}'
            }

            // }}}

        }, {

            // {{{ 削除ボタン

            reference       : 'btnRemove',
            bind: {
                handler     : '{button.remove.handler}',
                text        : '{button.remove.text}'
            }

            // }}}

        }, '-', {

            // {{{ 更新ボタン

            reference       : 'btnRefresh',
            bind: {
                handler     : '{button.refresh.handler}',
                text        : '{button.refresh.text}'
            }

            // }}}

        }, '->', {

            // {{{ 検索フィールド

            reference       : 'fieldSearch',
            itemId          : 'fieldSearch',
            xtype           : 'x-searchfield',
            width           : 150

            // }}}

        }],

        // }}}
        // {{{ bbar

        bbar: {

            // {{{ xtype

            xtype: 'pagingtoolbar',

            // }}}
            // {{{ displayInfo

            displayInfo: true,

            // }}}
            // {{{ store

            store: 'MFTest.EditListOtherScreenName.store.Lists'

            // }}}

        }

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
