/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:13
*/

/**
 * MFTest.Edit.view.main.Main Class
 *
 */
Ext.define('MFTest.Edit.view.main.Main', {

    // {{{ extend

    extend: 'MicroField.view.edit.Main',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.Edit.view.main.MainController',
        'MFTest.Edit.view.main.MainModel',
        'MFTest.Edit.view.edit.Edit'
    ],

    // }}}
    // {{{ xtype

    xtype: 'mftest-edit',

    // }}}
    // {{{ controller

    controller: 'mftest-edit-main',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-edit-main'
    },

    // }}}
    // {{{ config

    config: {

        // {{{ layout

        layout: 'card',

        // }}}
        // {{{ title

        title: _('MFTest.Edit:Title'),

        // }}}
        // {{{ items

        items: [{

            // {{{ 編集パネル

            xtype: 'mftest-edit-edit'

            // }}}

        }]

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
