/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:48
*/

/**
 * MFTest.Footer.view.main.Main Class
 *
 */
Ext.define('MFTest.Footer.view.main.Main', {

    // {{{ extend

    extend: 'Ext.toolbar.Toolbar',

    // }}}
    // {{{ xtype

    xtype: 'mftest-footer',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.Footer.view.main.MainController',
        'MFTest.Footer.view.main.MainModel'
    ],

    // }}}
    // {{{ controller

    controller: 'mftest-footer-main',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-footer-main'
    },

    // }}}
    // {{{ cls

    cls: 'x-mod-footer',

    // }}}
    // {{{ items

    items: ['->', 'MFTest.Footer - MicroField Version ' + MicroField.settings.version]

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
