/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:52
*/

/**
 * MFTest.EditOtherTable.view.main.Main Class
 *
 */
Ext.define('MFTest.EditOtherTable.view.main.Main', {

    // {{{ extend

    extend: 'MicroField.view.edit.Main',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.EditOtherTable.view.main.MainController',
        'MFTest.EditOtherTable.view.main.MainModel',
        'MFTest.EditOtherTable.view.edit.Edit'
    ],

    // }}}
    // {{{ xtype

    xtype: 'mftest-editothertable',

    // }}}
    // {{{ controller

    controller: 'mftest-editothertable-main',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-editothertable-main'
    },

    // }}}
    // {{{ config

    config: {

        // {{{ layout

        layout: 'card',

        // }}}
        // {{{ title

        title: _('MFTest.EditOtherTable:Title'),

        // }}}
        // {{{ items

        items: [{

            // {{{ 編集パネル

            xtype: 'mftest-editothertable-edit'

            // }}}

        }]

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
