<?php

// {{{ MFTest_Navigation_Filter

/**
 * MFTest_Navigation_Filter - MicroField SDK
 *
 * Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
 * http://www.xenophy.com
 *
 * generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:11
 */

class MFTest_Navigation_Filter {

    // {{{ doNothing

    public function doNothing() {

        // Nothing to do

    }

    // }}}

}

// }}}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
