/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 15:01:20
*/

/**
 * ナビゲーション ツリーストアクラス
 *
 */
Ext.define('MFTest.TabletNavigation.store.Tree', {

    // {{{ extend

    extend: 'Ext.data.TreeStore',

    // }}}
    // {{{ proxy

    proxy: {

        // {{{ type

        type: 'direct',

        // }}}
        // {{{ directFn

        directFn: 'MicroField.rpc.MFTest.TabletNavigation.Tree.readData',

        // }}}
        // {{{ reader

        reader: {

            // {{{ type

            type: 'json',

            // }}}
            // {{{ rootProperty

            rootProperty: 'children'

            // }}}

        }

        // }}}

    },

    // }}}
    // {{{ root

    rootProperty: {

        // {{{ expanded

        expanded: true,

        // }}}
        // {{{ rootProperty

        rootProperty: 'children'

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
