/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:57
*/

/**
 * MFTest.EditListNoDB.view.list.ListModel Class
 *
 */
Ext.define('MFTest.EditListNoDB.view.list.ListModel', {

    // {{{ extend

    extend: 'MicroField.view.editlist.ListModel',

    // }}}
    // {{{ alias

    alias: 'viewmodel.mftest-editlistnodb-list',

    // }}}
    // {{{ data

    data: {
    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
