/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:56
*/

/**
 * MFTest.EditListOtherTable.view.edit.EditModel Class
 *
 */
Ext.define('MFTest.EditListOtherTable.view.edit.EditModel', {

    // {{{ extend

    extend: 'MicroField.view.editlist.EditModel',

    // }}}
    // {{{ alias

    alias: 'viewmodel.mftest-editlistothertable-edit'

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
