/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.8.0 date: 2015/01/14 03:01:56
*/

/**
 * MFTest.EditListOtherTable.controller.Main Class
 *
 */
Ext.define('MFTest.EditListOtherTable.controller.Main', {

    // {{{ extend

    extend: 'MicroField.controller.editlist.Main',

    // }}}
    // {{{ config

    config: {

        // {{{ screenName

        screenName: 'editlistothertable',

        // }}}
        // {{{ XTypePrefix

        XTypePrefix: 'mftest-editlistothertable'

        // }}}


    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
