<?php

// {{{ MFTest_TabletNavigation_Filter

/**
 * MFTest_TabletNavigation_Filter - MicroField SDK
 *
 * Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
 * http://www.xenophy.com
 *
 * generated by MicroField CLI v0.7.3 date: 2015/01/12 15:01:20
 */

class MFTest_TabletNavigation_Filter {

    // {{{ doNothing

    public function doNothing() {

        // Nothing to do

    }

    // }}}

}

// }}}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
