/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:14
*/

/**
 * MFTest.EditOtherScreenName.view.edit.Edit Class
 *
 */
Ext.define('MFTest.EditOtherScreenName.view.edit.Edit', {

    // {{{ extend

    extend: 'MicroField.view.edit.Edit',

    // }}}
    // {{{ xtype

    xtype: 'mftest-editotherscreenname-edit',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.EditOtherScreenName.view.edit.EditController',
        'MFTest.EditOtherScreenName.view.edit.EditModel'
    ],

    // }}}
    // {{{ controller

    controller: 'mftest-editotherscreenname-edit',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-editotherscreenname-edit'
    },

    // }}}
    // {{{ config

    config: {

        // {{{ api

        api: {
            load    : 'MicroField.rpc.MFTest.EditOtherScreenName.Users.readData',
            submit  : 'MicroField.rpc.MFTest.EditOtherScreenName.Users.updateData'
        },

        // }}}
        // {{{ border

        border: false,

        // }}}
        // {{{ bodyPadding

        bodyPadding: 20,

        // }}}
        // {{{ defaults

        defaults: {
            labelAlign  : 'top'
        },

        // }}}
        // {{{ items

        items: [{
            xtype       : 'textfield',
            itemId      : 'textdatatextfield',
            name        : 'textdata',
            fieldLabel  : _('MFTest.EditOtherScreenName:field.Text'),
            width       : 300
        }],

        // }}}
        // {{{ tbar

        tbar: [{

            // {{{ 保存ボタン

            reference       : 'btnSave',
            bind: {
                handler     : '{button.save.handler}',
                text        : '{button.save.text}'
            }

            // }}}


        }, {

            // {{{ リセットボタン

            reference       : 'btnReset',
            bind: {
                handler     : '{button.reset.handler}',
                text        : '{button.reset.text}'
            }

            // }}}

        }],

        // }}}
        // {{{ trackResetOnLoad

        trackResetOnLoad: true

        // }}}

    }

    // }}}

    // </microfield-cmd-initconfiguration>

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
