/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/*
Copyright (c) 2015 Xenophy.CO.,LTD All rights Reserved.
http://www.xenophy.com

generated by MicroField CLI v0.7.3 date: 2015/01/12 09:01:19
*/

/**
 * MFTest.EditListNoDB.view.main.Main Class
 *
 */
Ext.define('MFTest.EditListNoDB.view.main.Main', {

    // {{{ extend

    extend: 'MicroField.view.editlist.Main',

    // }}}
    // {{{ xtype

    xtype: 'mftest-editlistnodb',

    // }}}
    // {{{ requires

    requires: [
        'MFTest.EditListNoDB.view.list.List',
        'MFTest.EditListNoDB.view.edit.Edit',
        'MFTest.EditListNoDB.view.main.MainController',
        'MFTest.EditListNoDB.view.main.MainModel'
    ],

    // }}}
    // {{{ controller

    controller: 'mftest-editlistnodb-main',

    // }}}
    // {{{ viewModel

    viewModel: {
        type: 'mftest-editlistnodb-main'
    },

    // }}}
    // {{{ config

    config: {

        // {{{ title

        title: _('MFTest.EditListNoDB:Title'),

        // }}}
        // {{{ items

        items: [{

            // {{{ xtype

            xtype: 'mftest-editlistnodb-list'

            // }}}

        }, {

            // {{{ xtype

            xtype: 'mftest-editlistnodb-edit'

            // }}}

        }]

        // }}}

    }

    // }}}

});

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * End:
 */
